"""Complete GemSpot KE database schema

Revision ID: 56b3b1644088
Revises: d6695ac50069
Create Date: 2026-07-28 16:02:24.557438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56b3b1644088'
down_revision = 'd6695ac50069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_color', sa.String(length=30), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'])

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matatu_route', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('gate_fee', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('till_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('power_sockets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_indoor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reservation_required', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vibe_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vibe_tag', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('caption', sa.String(length=150), nullable=True))
        batch_op.alter_column('weather_status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vibe_checks', schema=None) as batch_op:
        batch_op.alter_column('weather_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('caption')
        batch_op.drop_column('video_url')
        batch_op.drop_column('vibe_tag')

    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('reservation_required')
        batch_op.drop_column('is_indoor')
        batch_op.drop_column('power_sockets')
        batch_op.drop_column('till_number')
        batch_op.drop_column('gate_fee')
        batch_op.drop_column('matatu_route')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('category_id')
        batch_op.drop_column('venue_name')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('theme_color')

    # ### end Alembic commands ###
